name: WildFly Build

on:
  pull_request:
    branches:
      - '**'
    paths:
      - "**/pom.xml"
  workflow_dispatch:
    inputs:
      create_draft_release:
        description: 'Create GitHub draft release?'
        required: false
        default: false
        type: boolean
      jdk-distribution:
        description: 'JDK Distribution'
        required: false
        default: 'temurin'
        type: choice
        options:
          - temurin
          - semeru
          - microsoft
          - oracle
          - zulu
          - corretto
          - liberica

jobs:
  build-and-release:
    name: WildFly Build and Optional Draft Release
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Set up Corretto 11 (JDK 11)
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: ${{ inputs.jdk-distribution }}
          cache: 'maven'

      # Set up Maven settings for GitHub Packages authentication
      - name: Set up Maven settings for GitHub Packages
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
              <server>
                <id>github-lucene-solr</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
              <server>
                <id>github-xalan2</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>additional-repositories</id>
                <repositories>
                  <repository>
                    <id>github</id>
                    <url>https://maven.pkg.github.com/martinhickson/wildfly-core</url>
                    <releases>
                      <enabled>true</enabled>
                      <updatePolicy>never</updatePolicy>
                    </releases>
                    <snapshots>
                      <enabled>true</enabled>
                      <updatePolicy>never</updatePolicy>
                    </snapshots>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>additional-repositories</activeProfile>
            </activeProfiles>
          </settings>
          EOF

      - name: Clear any possible SNAPSHOT dependencies in the local maven repository
        run: |
          LOCAL_REPO="$HOME/.m2/repository"
          echo "Cleaning SNAPSHOTS from $LOCAL_REPO"
          if [ -d "$LOCAL_REPO" ]; then find "$LOCAL_REPO" -name "*SNAPSHOT*" | xargs -I {} rm -rfv "{}"; fi
        shell: bash

      - name: Build with Maven Java 11
        run: mvn -U -B install -Drelease=true -DskipTests=true -Denforcer.skip=true -Dcheckstyle.skip=true

      - name: Generate SHA-512 checksums for JARs
        run: |
          mkdir -p release-assets
          find ./ -type f -name 'wildfly*.jar' | while read jar; do
            fname=$(basename "$jar")
            if [[ "$jar" != *"/release-assets/"* && "$fname" != *"sources"* ]]; then 
              cp "$jar" "release-assets/$fname"
              sha512sum "$jar" | awk '{ print $1 }' > "release-assets/$fname.sha512"
            fi
          done
          zipname="wildfly-artifacts.zip"
          cd release-assets
          zip -r "../$zipname" . > /dev/null
          cd ..  
          sha512sum "$zipname" | awk '{ print $1 }' > "$zipname.sha512"
          rm -rf release-assets/
        shell: bash

      - name: Find WildFly and Preview ZIPs, generate SHA-512
        id: find_dist
        run: |
          echo "Listing all *.zip files:"
          find . -name "*.zip" -exec du -h {} \;

          echo "Listing all wildfly*.zip files in build/target:"
          find . -path "*/build/target/wildfly*.zip"

          # Find standard WildFly ZIP
          DIST_PATH=$(find . -path "*/dist/target/wildfly-*.zip" ! -name "wildfly-preview-*.zip" \
            ! -name "*src.zip" | head -n 1)
          if [[ -f "$DIST_PATH" ]]; then
            DIST_FILE=$(basename "$DIST_PATH")
            cp "$DIST_PATH" "./$DIST_FILE"
            sha512sum "$DIST_FILE" | awk '{ print $1 }' > "$DIST_FILE.sha512"
            echo "DIST_FILE_NAME=$DIST_FILE" >> $GITHUB_ENV
          else
            echo "WildFly distribution ZIP not found!"
            exit 1
          fi

          # Find standard WildFly ZIP SRC
          DIST_SRC_PATH=$(find . -path "*/dist/target/wildfly-*src.zip" ! -name "wildfly-preview-*.zip" \
            | head -n 1)
          if [[ -f "$DIST_SRC_PATH" ]]; then
            DIST_SRC_FILE=$(basename "$DIST_SRC_PATH")
            cp "$DIST_SRC_PATH" "./$DIST_SRC_FILE"
            sha512sum "$DIST_SRC_FILE" | awk '{ print $1 }' > "$DIST_SRC_FILE.sha512"
            echo "DIST_SRC_FILE_NAME=$DIST_SRC_FILE" >> $GITHUB_ENV
          else
            echo "WildFly distribution ZIP SRC not found!"
            exit 1
          fi

          # Find preview WildFly ZIP
          PREVIEW_PATH=$(find . -path "*/dist/target/wildfly-preview-*.zip" | head -n 1)
          if [[ -f "$PREVIEW_PATH" ]]; then
            PREVIEW_FILE=$(basename "$PREVIEW_PATH")
            cp "$PREVIEW_PATH" "./$PREVIEW_FILE"
            sha512sum "$PREVIEW_FILE" | awk '{ print $1 }' > "$PREVIEW_FILE.sha512"
            echo "PREVIEW_FILE_NAME=$PREVIEW_FILE" >> $GITHUB_ENV
          else
            echo "WildFly preview ZIP not found!"
            # Do not exit here, it's optional
          fi
        shell: bash

      - name: Create Draft Release (Optional)
        if: ${{ github.event.inputs.create_draft_release == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: draft-${{ github.run_number }}
          draft: true
          files: |
            ${{ env.DIST_FILE_NAME }}
            ${{ env.DIST_FILE_NAME }}.sha512
            ${{ env.DIST_SRC_FILE_NAME }}
            ${{ env.DIST_SRC_FILE_NAME }}.sha512
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
